# Generated by Django 3.1.5 on 2021-07-16 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210716_0206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='user1.jpg', upload_to='profile_pics'),
        ),
    ]
