# Generated by Django 3.2.7 on 2021-09-16 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='thumbnail',
            field=models.CharField(blank=True, max_length=2055, null=True),
        ),
    ]
